const API='https://pvwqxpqetdxtmqqypqjk.supabase.co/functions/v1/esf06-recadastro-api';
const BOOLS=[['acamado','Acamado'],['deficiencia','Deficiência'],['transtorno_mental_alto_risco','Transtorno mental de alto risco'],['deficiencia_intelectual','Deficiência intelectual'],['saneamento_ruim','Saneamento inadequado'],['desnutricao','Desnutrição'],['abuso_substancia_psicoativa','Uso de substância psicoativa'],['adulto_sem_renda','Adulto sem renda'],['analfabetismo','Analfabetismo'],['menor_2_anos','Criança menor de 2 anos'],['maior_60_anos','Pessoa com 60 anos ou mais'],['hipertensao','Hipertensão'],['diabetes','Diabetes'],['hemodialise','Hemodiálise'],['gestante','Gestante'],['povos_originarios','Povos originários'],['doencas_transmissiveis','Hepatites / hanseníase / leishmaniose / tuberculose'],['problema_respiratorio','Problema respiratório com uso de medicamento'],['lgbt','População LGBT'],['cancer','Câncer']];
let rows=[],current=null,draft={},key=localStorage.getItem('esf06_key')||'';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2200)}
async function api(path='',opts={}){const sep=path.includes('?')?'&':'?';const url=API+path+sep+'k='+encodeURIComponent(key);const h={...(opts.headers||{})};if(opts.body)h['content-type']='text/plain;charset=UTF-8';let r;try{r=await fetch(url,{...opts,headers:h})}catch(e){throw new Error('Não foi possível conectar ao Supabase')};let j;try{j=await r.json()}catch(e){throw new Error('Resposta inválida do servidor ('+r.status+')')};if(!r.ok)throw new Error((j.error||'Falha')+' ('+r.status+')');return j}
function riskLabel(r){return({alto:'Alto risco',medio:'Médio risco',baixo:'Baixo risco',sem_risco:'Sem risco',pendente:'Pendente'})[r]||'Pendente'}
async function load(){ $('sync').textContent='atualizando…';const j=await api('?action=list');rows=j.rows||[];$('sync').textContent='dados atualizados';fillStreets();render()}
function fillStreets(){const cur=$('fstreet').value;const vals=[...new Set(rows.map(x=>x.street).filter(Boolean))].sort();$('fstreet').innerHTML='<option value="">Todas as ruas</option>'+vals.map(x=>'<option>'+esc(x)+'</option>').join('');$('fstreet').value=cur}
function render(){
 const q=$('q').value.trim().toLowerCase(),fs=$('fs').value,fr=$('fr').value,st=$('fstreet').value;
 const filtered=rows.filter(x=>{const r=x.recadastro||{};const blob=[x.family_code,x.responsible_name,x.street,x.number,x.neighborhood].join(' ').toLowerCase();return(!q||blob.includes(q))&&(!fs||(fs==='concluido'?r.concluido:!r.concluido))&&(!fr||(r.risco||'pendente')===fr)&&(!st||x.street===st)});
 $('st').textContent=rows.length;$('sp').textContent=rows.filter(x=>!x.recadastro?.concluido).length;$('sd').textContent=rows.filter(x=>x.recadastro?.concluido).length;$('sh').textContent=rows.filter(x=>x.recadastro?.risco==='alto').length;
 $('list').innerHTML=filtered.length?filtered.map(x=>{const r=x.recadastro||{};const addr=[x.street,x.number&&'nº '+x.number,x.reference,x.neighborhood].filter(Boolean).join(', ');return '<article class="fam" data-code="'+esc(x.family_code)+'"><div class="top"><h3>'+esc(x.responsible_name||'Responsável não informado')+'</h3><span class="badge '+esc(r.risco||'pendente')+'">'+riskLabel(r.risco)+'</span></div><div class="meta">Família '+esc(x.family_code)+' · '+esc(r.moradores??x.operational_member_count??x.official_member_count??'—')+' morador(es)</div><div>'+esc(addr||'Endereço pendente')+'</div><button class="open">Abrir ficha</button></article>'}).join(''):'<div class="empty">Nenhuma família encontrada.</div>';
 document.querySelectorAll('.open').forEach(b=>b.onclick=()=>openFamily(b.closest('.fam').dataset.code));
}
function setToggle(field,value){const el=document.querySelector('.tog[data-field="'+field+'"]');if(!el)return;el.querySelectorAll('button').forEach(b=>{b.className='';const v=b.dataset.v==='true'?true:b.dataset.v==='false'?false:null;if(v===value)b.classList.add(value===true?'yes':value===false?'no':'unk')})}
function openFamily(code){current=rows.find(x=>x.family_code===code);const r=current.recadastro||{};draft={...r};$('name').textContent=current.responsible_name||'Responsável não informado';$('code').textContent='Família '+current.family_code;['street','number','neighborhood','postal_code','city','state','reference'].forEach(k=>$(k).value=current[k]??'');['data_recadastramento','moradores','comodos','distancia_km'].forEach(k=>$(k).value=r[k]??'');$('bools').innerHTML=BOOLS.map(([k,l])=>'<div style="margin:12px 0"><label>'+esc(l)+'</label><div class="tog" data-field="'+k+'"><button data-v="true">Sim</button><button data-v="false">Não</button><button data-v="null">Não confirmado</button></div></div>').join('');BOOLS.forEach(([k])=>setToggle(k,r[k]));document.querySelectorAll('.tog button').forEach(b=>b.onclick=()=>{const f=b.parentElement.dataset.field;const v=b.dataset.v==='true'?true:b.dataset.v==='false'?false:null;draft[f]=v;setToggle(f,v)});$('dlg').showModal();$('bar').style.display='grid'}
function closeDialog(){$('dlg').close();$('bar').style.display='none';current=null;draft={}}
async function save(){
 if(!current)return;const data={};
 ['data_recadastramento','moradores','comodos','distancia_km'].forEach(k=>{let v=$(k).value;if(k==='moradores'||k==='comodos')v=v===''?null:Number(v);if(k==='distancia_km')v=v===''?null:Number(v);data[k]=v===''?null:v});
 BOOLS.forEach(([k])=>data[k]=(k in draft)?draft[k]:null);
 const address={};['street','number','neighborhood','postal_code','city','state','reference'].forEach(k=>address[k]=$(k).value.trim());
 $('save').disabled=true;$('save').textContent='Salvando…';
 try{const j=await api('',{method:'POST',body:JSON.stringify({family_code:current.family_code,data,address})});const i=rows.findIndex(x=>x.family_code===current.family_code);rows[i]={...rows[i],...j.family,recadastro:j.recadastro};toast('Salvo com sucesso');closeDialog();render()}catch(e){toast(e.message)}finally{$('save').disabled=false;$('save').textContent='Salvar alterações'}
}
async function enter(){key=$('access').value.trim();if(!key)return toast('Digite o código');try{await load();localStorage.setItem('esf06_key',key);$('login').hidden=true;$('app').hidden=false;$('hdr').hidden=false}catch(e){toast('Código inválido ou serviço indisponível')}}
$('enter').onclick=enter;$('access').onkeydown=e=>{if(e.key==='Enter')enter()};$('reload').onclick=()=>load().catch(e=>toast(e.message));$('logout').onclick=()=>{localStorage.removeItem('esf06_key');location.reload()};$('close').onclick=closeDialog;$('cancel').onclick=closeDialog;$('save').onclick=save;['q','fs','fr','fstreet'].forEach(id=>$(id).addEventListener(id==='q'?'input':'change',render));if(key){$('access').value=key;enter()}if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});